name: Remote SSH command
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: execute command
        run: |
          source /home/woju5294/nodevenv/repositories/bot/Gerard-Larcher-bot/16/bin/activate && cd /home/woju5294/repositories/bot/Gerard-Larcher-bot
          pm2 start dist/index.js --name"Gérard Larcher bot"